# Generated by Django 5.2.5 on 2025-08-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='course_previews/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
