# Generated by Django 5.2.5 on 2025-08-23 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_course_image_preview_alter_course_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='course',
        ),
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('passing_score', models.PositiveIntegerField(default=5)),
                ('time_limit', models.DurationField(blank=True, null=True)),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='catalog.chapter')),
            ],
        ),
    ]
