# Generated by Django 5.2.5 on 2025-08-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_material_course_remove_video_course_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='kind',
            field=models.CharField(choices=[('required', 'Material obligatorio'), ('extra', 'Material de refuerzo')], default='required', max_length=20),
        ),
    ]
